name: CROUS Checker

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  check_crous:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          # Explanation:
          #   chromium-browser: The actual browser
          #   chromium-chromedriver: Matches the Chromium version installed

      - name: Install Python Dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Run the script
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: python src/main.py

      - name: Commit and push changes if detected
        # only needed if you're committing last_result.txt changes
        if: always()
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add src/last_result.txt
          git commit -m "Update last_result.txt" || echo "No changes to commit"
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git master
